alias: current_harmony_input
trigger:
  platform: event
  event_type: homeassistant_start
action:
  - delay:
      seconds: 30
  - service: input_select.select_option
    data_template:
      entity_id: input_select.bedroom_tv
      option: '{{ states.remote.harmony_hub.attributes.current_activity }}'