###############################################################################
# Home Assistant Package - Media -> Sonarr
#  @author         :   Thomas Baxter
#  @date           :   17/02/2019
#  @version        :   0.1
#  @description    :   Configuration for Sonarr
#  @changelog      :   v0.1 - Initial Version
###############################################################################

###############################################################################
## Customize
###############################################################################
# homeassistant:
#   customize:

###############################################################################
## Group
###############################################################################
group:
  sonarr:
    name: Sonarr
    control: hidden
    entities:
      - weblink.sonarr
      - sensor.sonarr_status
      - sensor.sonarr_series
      - sensor.sonarr_upcoming
      - sensor.sonarr_queue
      - sensor.sonarr_wanted

###############################################################################
## Sensor
###############################################################################
sensor:
  ###
  ## Sonarr
  ###
  - platform: sonarr
    api_key: !secret sonarr_apikey
    host: !secret sonarr_host
    port: !secret sonarr_port
    monitored_conditions:
      - upcoming
      - queue
      - series
      - wanted
      - status
    days: 28
  ###
  ## Sonarr Upcoming Media
  ###
  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_apikey
    host: !secret sonarr_host
    port: !secret sonarr_port
    days: 7
    max: 20

###############################################################################
## Weblink
###############################################################################
weblink:
  entities:
    - name: Sonarr
      url: !secret sonarr_url
      icon: mdi:download
