netatmo:
  api_key: !secret netatmo_apikey
  secret_key: !secret netatmo_secretkey
  username: !secret netatmo_username
  password: !secret netatmo_password

sensor:
  - platform: netatmo
    modules:
      Indoor:
        - temperature
        - co2
        - pressure
        - noise
        - humidity
        - min_temp
        - max_temp
        - wifi_status
      Outdoor:
        - temperature
        - pressure
        - humidity
        - min_temp
        - max_temp
        - rf_status
        - battery_vp