alias: 'Remote start TV Channel Change'
trigger:
  platform: state
  entity_id: remote.harmony_hub
action:
  service: input_select.select_option
  data_template:
    entity_id: input_select.bedroom_tv