###############################################################################
# Home Assistant Package - Home Assistant
#  @author         :   Thomas Baxter
#  @date           :   16/02/2019
#  @version        :   0.1
#  @description    :   Configuration for Home Assistant Related Functions
#  @changelog      :   v0.1 - Initial Version
###############################################################################

###############################################################################
## Customize
###############################################################################
homeassistant:
  customize:
    sensor.ha_current_version:
      friendly_name: Current Version
      icon: mdi:home-assistant
    sensor.ha_latest_version:
      friendly_name: Latest Version
      icon: mdi:home-assistant
    sensor.ha_uptime_hours:
      friendly_name: Uptime
      icon: mdi:home-assistant

###############################################################################
## Groups
###############################################################################
group:
  homeassistant:
    name: Home Assistant
    control: hidden
    entities:
      - sensor.ha_uptime_hours
      - sensor.ha_current_version
      - sensor.ha_latest_version

###############################################################################
## Sensors
###############################################################################
sensor:
  ###
  ## Latest Version (Docker)
  ###
  - platform: version
    source: docker
    name: HA Latest Version
  ###
  ## Current Version
  ###
  - platform: version
    source: local
    name: HA Current Version
  ###
  ## World Time - New York
  ###
  - platform: uptime
    name: HA Uptime Hours
    unit_of_measurement: hours