###############################################################################
# Home Assistant Package - Weather -> BOM
#  @author         :   Thomas Baxter
#  @date           :   17/02/2019
#  @version        :   0.1
#  @description    :   Configuration for BOM Weather
#  @changelog      :   v0.1 - Initial Version
###############################################################################

###############################################################################
## Customize
###############################################################################
# homeassistant:
#   customize:

###############################################################################
## Group
###############################################################################
group:
  weather_bom:
    name: BOM Tamworth Airport
    control: hidden
    entities:
      - sensor.bom_local_time
      - sensor.bom_air_temp_c
      - sensor.bom_feels_like_c
      - sensor.bom_cloud
      - sensor.bom_relative_humidity
      - sensor.bom_pressure_mb
      - sensor.bom_rain_today

###############################################################################
## Sensor
###############################################################################
sensor:
  - platform: bom
    station: IDN60801.95762
    monitored_conditions:
      - apparent_t
      - cloud
      - cloud_base_m
      - cloud_oktas
      - cloud_type_id
      - cloud_type
      - delta_t
      - gust_kmh
      - gust_kt
      - air_temp
      - dewpt
      - local_date_time
      - local_date_time_full
      - press
      - press_qnh
      - press_msl
      - press_tend
      - rain_trace
      - rel_hum
      - vis_km
      - weather
      - wind_dir
      - wind_spd_kmh
      - wind_spd_kt

###############################################################################
## Weblink
###############################################################################
# weblink:
#   entities:
