###############################################################################
# Home Assistant Package - Weather -> Yr.no
#  @author         :   Thomas Baxter
#  @date           :   16/02/2019
#  @version        :   0.1
#  @description    :   Configuration for Yr.no
#  @changelog      :   v0.1 - Initial Version
###############################################################################

###############################################################################
## Customize
###############################################################################
# homeassistant:
#   customize:

###############################################################################
## Group
###############################################################################
group:
  yrno:
    name: Yr.no
    control: hidden
    entities:
      - sensor.yr_temperature
      - sensor.yr_pressure
      - sensor.yr_humidity
      - sensor.yr_pressure
      - sensor.yr_precipitation

###############################################################################
## Sensors
###############################################################################
sensor:
  ###
  ## Yr.no
  ###
  - platform: yr
    name: yr
    forecast: 0
    monitored_conditions:
      - temperature
      # - symbol
      - precipitation
      # - windSpeed
      - pressure
      # - windDirection
      - humidity
      # - fog
      # - cloudiness
      # - lowClouds
      # - mediumClouds
      # - highClouds
      # - dewpointTemperature

###############################################################################
## Weblink
###############################################################################
# weblink:
#   entities: