homeassistant:
  customize:
    "geo_location.nsw_fire_service_feed_*":
      icon: mdi:map

geo_location:
  - platform: nsw_rural_fire_service_feed
    entity_namespace: "nswrfs"
    radius: 75
    categories:
      - 'Emergency Warning'
      - 'Watch and Act'
      - 'Advice'
      - 'Not Applicable'