###############################################################################
# Home Assistant Package - Date & Time
#  @author         :   Thomas Baxter
#  @date           :   16/02/2019
#  @version        :   0.1
#  @description    :   Configuration for Date & Time Functions
#  @changelog      :   v0.1 - Initial Version
###############################################################################

###############################################################################
## Customize
###############################################################################
homeassistant:
  customize:
    sensor.date:
      friendly_name: Current Date
    sensor.time:
      friendly_name: Current Time - Home
    sensor.time_utc:
      friendly_name: Current Time - UTC
    sensor.london_time:
      friendly_name: Current Time - UK (London)
    sensor.new_york_time:
      friendly_name: Current Time - US (New York)

###############################################################################
## Groups
###############################################################################
group:
  time:
    name: Date & Time
    control: hidden
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_utc
      - sensor.london_time
      - sensor.new_york_time

###############################################################################
## Sensors
###############################################################################
sensor:
  ###
  ## Local Time
  ###
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_utc'
  ###
  ## World Time - London
  ###
  - platform: worldclock
    time_zone: Europe/London
    name: London Time
  ###
  ## World Time - New York
  ###
  - platform: worldclock
    time_zone: America/New_York
    name: New York Time