title: HA Settings
icon: mdi:settings
cards:
  - !include custom_header.yaml
  - type: vertical-stack
    cards:
      - type: entities
        title: Home Assistant
        show_header_toggle: false
        entities:
          - sensor.home_assistant_uptime
          - sensor.ha_current_version
          - sensor.ha_latest_version
          - type: call-service
            icon: mdi:cube-send
            name: Update Lovelace
            action_name: Update Lovelace
            service: shell_command.lovelace_gen
      - type: custom:tracker-card
        title: Custom Items Tracker
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
  # - type: custom:group-card
  #   card:
  #     type: entities
  #     title: Devices
  #     show_header_toggle: false
  #   group: group.all_devices
  - type: custom:monster-card
    card:
      type: entities
      title: Things that are broken
      show_header_toggle: false
    filter:
      include:
        - state: "unknown"
      exclude:
        - entity_id: group.*
  - type: entities
    title: Groups
    show_header_toggle: false
    entities:
      - type: custom:fold-entity-row
        head: group.all_automations
        group_config:
          secondary_info: last-changed
      - type: custom:auto-entities
        card: 
          type: custom:fold-entity-row
          head:
            type: section
            label: Devices at Home
          group_config:
            secondary_info: last-changed
        filter:
          include:
            - domain: device_tracker
              state: "home"
      - type: custom:auto-entities
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Devices not at Home
          group_config:
            secondary_info: last-changed
        filter:
          include:
            - domain: device_tracker
              state: "not_home"
      - type: custom:fold-entity-row
        head: group.all_geolocation_events
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: all.lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.all_remotes
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.all_scripts
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.all_switches
        group_config:
          secondary_info: last-changed