title: HA Settings
icon: mdi:settings
cards:
  - !include custom_header.yaml
  - type: entities
    title: Home Assistant
    show_header_toggle: false
    entities:
      - sensor.home_assistant_uptime
      - sensor.ha_current_version
      - sensor.ha_latest_version
      - type: call-service
        icon: mdi:cube-send
        name: Update Lovelace
        action_name: Update Lovelace
        service: shell_command.lovelace_gen
  - type: custom:tracker-card
    title: HA Custom Items Tracker
    trackers:
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
  - type: entities
    title: Server
    show_header_toggle: false
    entities:
      - sensor.ipv4_address_eno1
      - sensor.ipv6_address_eno1
      - sensor.external_ipv4
      - sensor.last_boot
      - sensor.disk_free
      - sensor.disk_use_percent
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.memory_free
      - sensor.memory_use
      - sensor.network_in_eno1
      - sensor.network_out_eno1
  - type: custom:group-card
    card:
      type: entities
      title: Devices
      show_header_toggle: false
    group: group.all_devices
  - type: custom:monster-card
    card:
      type: entities
      title: Things that are broken
    filter:
      include:
        - state: "unknown"
      exclude:
        - entity_id: group.*
