title: tbsmartho.me

resources:
  - url: /local/upcoming-media-card.js?v=0.3.4
    type: js
  - url: /local/tracker-card.js?v=0.3.0
    type: js
  - url: /local/group-card.js?v=0.0.2
    type: js
  - url: /local/monster-card.js?v=0.2.3
    type: js
  - url: /local/useful-markdown-card.js?v=dfc268
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.2.1
    type: module
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.2.9
    type: js
  - url: /local/waze-card/waze-card.js?v=1.1.1
    type: js
  - url: /local/mini-media-player-bundle.js?v=1.0.0
    type: module
  - url: /local/card-tools.js?v=297fcc
    type: js
  - url: /local/fold-entity-row.js?v=6d11d3
    type: js
  - url: /local/auto-entities.js?v=3cfd04
    type: js
  - url: /local/list-card.js?v=v0.0.7
    type: js
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css

views:
  - !include 00_home_view.yaml
  - !include 01_house_view.yaml
  - !include 02_weather_view.yaml
  - !include 03_media_view.yaml
  - !include 04_network_view.yaml
  - !include 05_online_view.yaml
  - !include 06_lights_view.yaml
  - !include 07_flightradar_view.yaml
  - !include 08_docker_view.yaml
  - !include 09_news_view.yaml
  - !include 99_hasettings_view.yaml
  - !include temp.yaml