###############################################################################
# Home Assistant Package - Pi-Hole
#  @author         :   Thomas Baxter
#  @date           :   16/02/2019
#  @version        :   0.1
#  @description    :   Configuration for Pi-Hole
#  @changelog      :   v0.1 - Initial Version
###############################################################################

###############################################################################
## Customize
###############################################################################
# homeassistant:
#   customize:

###############################################################################
## Group
###############################################################################
group:
  pi_hole:
    name: Pi-Hole
    control: hidden
    entities:
      - weblink.pi_hole_admin_panel
      - sensor.pi_hole_status
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - sensor.pi_hole_dns_queries_today
      - sensor.pi_hole_domains_blocked
      - sensor.pi_hole_dns_queries_cached
      - sensor.pi_hole_dns_queries_forwarded
      - sensor.pi_hole_dns_unique_clients
      - sensor.pi_hole_dns_unique_domains
      - sensor.pi_hole_seen_clients

###############################################################################
## Sensors
###############################################################################
sensor:
  ###
  ## Pi-Hole
  ###
  - platform: pi_hole
    host: !secret pihole_host
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today
      - domains_being_blocked
      - queries_cached
      - queries_forwarded
      - unique_clients
      - unique_domains
      - clients_ever_seen
  ###
  ## Command Line - Pi-Hole Status
  ###
  - platform: command_line
    name: Pi-Hole Status
    command: curl -X GET 'http://192.168.15.30/admin/api.php?status'
    value_template: >
      {{ value_json.status }}

###############################################################################
## Weblink
###############################################################################
weblink:
  entities:
    - name: Pi-Hole Admin Panel
      url: !secret pihole_url
      icon: mdi:lan