###############################################################################
# Home Assistant Package - Media -> Radarr
#  @author         :   Thomas Baxter
#  @date           :   17/02/2019
#  @version        :   0.1
#  @description    :   Configuration for Radarr
#  @changelog      :   v0.1 - Initial Version
###############################################################################

###############################################################################
## Customize
###############################################################################
# homeassistant:
#   customize:

###############################################################################
## Group
###############################################################################
group:
  radarr:
    name: Radarr
    control: hidden
    entities:
      - weblink.radarr
      - sensor.radarr_status
      - sensor.radarr_movies
      - sensor.radarr_upcoming

###############################################################################
## Sensor
###############################################################################
sensor:
  ###
  ## Radarr
  ###
  - platform: radarr
    api_key: !secret radarr_apikey
    host: !secret radarr_host
    port: !secret radarr_port
    monitored_conditions:
      - movies
      - upcoming
      - status
    days: 28
  ###
  ## Radarr Upcoming Media
  ###
  - platform: radarr_upcoming_media
    api_key: !secret radarr_apikey
    host: !secret radarr_host
    port: !secret radarr_port
    days: 120
    max: 20

###############################################################################
## Weblink
###############################################################################
weblink:
  entities:
    - name: Radarr
      url: !secret radarr_url
      icon: mdi:download
