###############################################################################
# Home Assistant Package - Fuelcheck
#  @author         :   Thomas Baxter
#  @date           :   17/02/2019
#  @version        :   0.1
#  @description    :   Configuration for Fuelcheck
#  @changelog      :   v0.1 - Initial Version
###############################################################################

###############################################################################
## Customize
###############################################################################
homeassistant:
  customize:
    sensor.fuelcheck_caltex_tamworth_orana_p98:
      friendly_name: Caltex Vortex98 (White Street)
      icon: mdi:fuel

    sensor.fuelcheck_bp_tamworth_p98:
      friendly_name: BP Ultimate98 (Viaduct)
      icon: mdi:fuel

###############################################################################
## Group
###############################################################################
group:
  fuelprice:
    name: Fuel Prices
    control: hidden
    entities:
      - sensor.fuelcheck_caltex_tamworth_orana_p98
      - sensor.fuelcheck_bp_tamworth_p98

###############################################################################
## Sensor
###############################################################################
sensor:
  ###
  ## Fuelcheck BP Viaduct
  ###
  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    name: BP Viaduct
    fuel_types: P98
    station_id: 1145
  ###
  ## Fuelcheck Caltex White St
  ###
  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    name: Caltex White Street
    fuel_types: P98
    station_id: 16921

###############################################################################
## Weblink
###############################################################################
# weblink:
#   entities:
