###############################################################################
# Home Assistant Package - Media -> Plex
#  @author         :   Thomas Baxter
#  @date           :   16/02/2019
#  @version        :   0.1
#  @description    :   Configuration for Plex
#  @changelog      :   v0.1 - Initial Version
###############################################################################

###############################################################################
## Customize
###############################################################################
# homeassistant:
#   customize:

###############################################################################
## Group
###############################################################################
group:
  plex:
    name: Plex
    control: hidden
    entities:
      - weblink.plex
      - weblink.tautulli
      - sensor.plex_topmovie
      - sensor.plex_toptvshow
      - sensor.plex_topuser

###############################################################################
## Sensors
###############################################################################
sensor:
  ###
  ## Plex
  ###
  - platform: plex
    host: !secret plex_host
    port: !secret plex_port
    token: !secret plex_token
    include_non_clients: true
    show_all_controls: true
    entity_namespace: plex
  ###
  ## Tautulli
  ###
  - platform: tautulli
    api_key: !secret plex_tautulli_apikey
    host: !secret plex_tautulli_host
    port: !secret plex_tautulli_port
    monitored_users:
      - !secret plex_tautulli_user1
  ###
  ## Plex Recently Added
  ###
  - platform: plex_recently_added
    token: !secret plex_token
    host: !secret plex_host
    port: !secret plex_port
    download_images: false
    max: 20
  ###
  ## Template
  ###
  - platform: template
    sensors:
      plex_topmovie:
        friendly_name: Plex Top Movie
        value_template: "{{state_attr('sensor.tautulli', 'Top Movie')}}"
      plex_toptvshow:
        friendly_name: Plex Top TV Show
        value_template: "{{state_attr('sensor.tautulli', 'Top TV Show')}}"
      plex_topuser:
        friendly_name: Plex Top User
        value_template: "{{state_attr('sensor.tautulli', 'Top User')}}"

###############################################################################
## Weblink
###############################################################################
weblink:
  entities:
    - name: Plex
      url: !secret plex_url
      icon: mdi:television-guide
    - name: Tautulli
      url: !secret plex_tautulli_url
      icon: mdi:television-guide